### PR TITLE
Absolute bounds

### PR DESCRIPTION
**Pull request by lflake**

### CODE REVIEW

**Comment by lflake** [comment]
@bstabler  -- it sounds like this might need to be used soon for HTS weighting; can we merge this one?

**Comment by bstabler** [comment]
@lflake - please PR to develop instead of master.  Thanks.

**Comment by lflake** [comment]
Done -- looks like the CI build is failing with this error in a few places, which I don't think is related to the code in the commits for this PR?

E   ModuleNotFoundError: No module named 'cytoolz'

**Comment by lflake** [comment]
I see this is an issue on the other PR as well/is already known

**Comment by bstabler** [comment]
this looks good, thanks

**Pull request merged**
